[workspace]
resolver = "2"
members = [
  "crates/tsuzuri",
  # "crates/tsuzuri-dynamodb",
  # "crates/tsuzuri-libsql",
]

[workspace.metadata.spellcheck]
config = "spellcheck.toml"

[workspace.package]
rust-version = "1.86.0"
